/**
 * App Redux Action Types
 */

// Auth Actions
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const FILTER_CHANGE = "FILTER_CHANGE";
export const SET_FILTERS = "SET_FILTERS";
export const COLLAPSED_SIDEBAR = "COLLAPSED_SIDEBAR";
export const DARK_MODE = "DARK_MODE";
export const DARK_MODE_SUCCESS = "DARK_MODE_SUCCESS";
export const DARK_MODE_FAILURE = "DARK_MODE_FAILURE";
export const BOXED_LAYOUT = "BOXED_LAYOUT";
export const RTL_LAYOUT = "RTL_LAYOUT";
export const MINI_SIDEBAR = "MINI_SIDEBAR";
export const SEARCH_FORM_ENABLE = "SEARCH_FORM_ENABLE";
export const ACTIVATE_SIDEBAR_FILTER = "ACTIVATE_SIDEBAR_FILTER";
export const TOGGLE_SIDEBAR_IMAGE = "TOGGLE_SIDEBAR_IMAGE";
export const SET_SIDEBAR_IMAGE = "SET_SIDEBAR_IMAGE";
export const SET_LANGUAGE = "SET_LANGUAGE";
export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const GET_PERMISSIONS_FAILURE = "GET_PERMISSIONS_FAILURE";
export const GET_PERMISSIONS_SUCCESS = "GET_PERMISSIONS_SUCCESS";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// Sidebar
export const TOGGLE_MENU = "TOGGLE_MENU";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";
export const GET_USER_CONFIG_SETTINGS = "GET_USER_CONFIG_SETTINGS";
export const GET_USER_CONFIG_SETTINGS_SUCCESS =
  "GET_USER_CONFIG_SETTINGS_SUCCESS";
export const GET_USER_CONFIG_SETTINGS_FAILURE =
  "GET_USER_CONFIG_SETTINGS_FAILURE";

// user
export const ADD_USER_INFO = "ADD_USER_INFO";
export const ADD_USER_INFO_SUCCESS = "ADD_USER_INFO_SUCCESS";
export const ADD_USER_INFO_FAILURE = "ADD_USER_INFO_FAILURE";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE";
export const DELETE_USER = "GET_USER_LIST";
export const DELETE_USER_SUCCESS = "GET_USER_LIST_SUCCESS";
export const DELETE_USER_FAILURE = "GET_USER_LIST_FAILURE";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const GET_CSV_USER_LIST = "GET_CSV_USER_LIST";
export const GET_CSV_USER_LIST_SUCCESS = "GET_CSV_USER_LIST_SUCCESS";
export const GET_CSV_USER_LIST_FAILURE = "GET_CSV_USER_LIST_FAILURE";

// lab
export const GET_LAB_INFO_DATA = "GET_LAB_INFO_DATA";
export const GET_LAB_INFO_DATA_SUCCESS = "GET_LAB_INFO_DATA_SUCCESS";
export const GET_LAB_INFO_DATA_FAILURE = "GET_LAB_INFO_DATA_FAILURE";
export const GET_SELECTED_LAB_INFO_DATA = "GET_SELECTED_LAB_INFO_DATA";
export const GET_SELECTED_LAB_INFO_DATA_SUCCESS =
  "GET_SELECTED_LAB_INFO_DATA_SUCCESS";
export const GET_SELECTED_LAB_INFO_DATA_FAILURE =
  "GET_SELECTED_LAB_INFO_DATA_FAILURE";
export const ADD_LAB_DETAILS = "ADD_LAB_DETAILS";
export const ADD_LAB_DETAILS_SUCCESS = "ADD_LAB_DETAILS_SUCCESS";
export const ADD_LAB_DETAILS_FAILURE = "ADD_LAB_DETAILS_FAILURE";
// casess
export const GET_CASESS = "GET_CASESS";
export const GET_CASESS_FAILURE = "GET_CASESS_FAILURE";
export const GET_CASESS_SUCCESS = "GET_CASESS_SUCCESS";
export const GET_CSV_CASESS = "GET_CSV_CASESS";
export const GET_CSV_CASESS_FAILURE = "GET_CSV_CASESS_FAILURE";
export const GET_CSV_CASESS_SUCCESS = "GET_CSV_CASESS_SUCCESS";
export const DELETE_CASESS = "DELETE_CASESS";
export const DELETE_CASESS_FAILURE = "DELETE_CASESS_FAILURE";
export const DELETE_CASESS_SUCCESS = "DELETE_CASESS_SUCCESS";
export const REMOVE_DELETE_CASESS = "REMOVE_DELETE_CASESS";
export const GET_CASESS_CSV = "GET_CASESS_CSV";
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
export const GET_DOCUMENTS_FAILURE = "GET_DOCUMENTS_FAILURE";
export const GET_PRACTICE_SHIPPING = "GET_PRACTICE_SHIPPING";
export const GET_PRACTICE_SHIPPING_SUCCESS = "GET_PRACTICE_SHIPPING_SUCCESS";
export const GET_PRACTICE_SHIPPING_FAILURE = "GET_PRACTICE_SHIPPING_FAILURE";
export const GET_DOCUMENTS_VIEW = "GET_DOCUMENTS_VIEW";
export const GET_DOCUMENTS_VIEW_FAILURE = "GET_DOCUMENTS_VIEW_FAILURE";
export const GET_DOCUMENTS_VIEW_SUCCESS = "GET_DOCUMENTS_VIEW_SUCCESS";
export const DELETE_DOCUMENTS = "DELETE_DOCUMENTS";
export const DELETE_DOCUMENTS_FAILURE = "DELETE_DOCUMENTS_FAILURE";
export const DELETE_DOCUMENTS_SUCCESS = "DELETE_DOCUMENTS_SUCCESS";
export const SEND_DOCUMENTS_TO_LAB = "SEND_DOCUMENTS_TO_LAB";
export const SEND_DOCUMENTS_TO_LAB_FAILURE = "SEND_DOCUMENTS_TO_LAB_FAILURE";
export const SEND_DOCUMENTS_TO_LAB_SUCCESS = "SEND_DOCUMENTS_TO_LAB_SUCCESS";

// proudct
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const GET_PRODUCT_DATA_SUCCESS = "GET_PRODUCT_DATA_SUCCESS";
export const GET_PRODUCT_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";
export const GET_PRODUCT_GROUP_DATA = "GET_PRODUCT_GROUP_DATA";
export const GET_PRODUCT_GROUP_DATA_SUCCESS = "GET_PRODUCT_GROUP_DATA_SUCCESS";
export const GET_PRODUCT_GROUP_DATA_FAILURE = "GET_PRODUCT_GROUP_DATA_FAILURE";
export const DELETE_PRODUCT_DATA = "DELETE_PRODUCT_DATA";
export const DELETE_PRODUCT_DATA_SUCCESS = "DELETE_PRODUCT_DATA_SUCCESS";
export const DELETE_PRODUCT_DATA_FAILURE = "GET_PRODUCT_DATA_FAILURE";
export const DELETE_PRODUCT_GROUP_DATA = "DELETE_PRODUCT_GROUP_DATA";
export const DELETE_PRODUCT_GROUP_DATA_SUCCESS =
  "DELETE_PRODUCT_GROUP_DATA_SUCCESS";
export const DELETE_PRODUCT_GROUP_DATA_FAILURE =
  "DELETE_PRODUCT_GROUP_DATA_FAILURE";

//material
export const GET_MATERIAL_DATA = "GET_MATERIAL_DATA";
export const GET_MATERIAL_DATA_SUCCESS = "GET_MATERIAL_DATA_SUCCESS";
export const GET_MATERIAL_DATA_FAILURE = "GET_MATERIAL_DATA_FAILURE";
export const GET_MATERIAL_GROUP_DATA = "GET_MATERIAL_GROUP_DATA";
export const GET_MATERIAL_GROUP_DATA_SUCCESS =
  "GET_MATERIAL_GROUP_DATA_SUCCESS";
export const GET_MATERIAL_GROUP_DATA_FAILURE =
  "GET_MATERIAL_GROUP_DATA_FAILURE";

//itemoptions
export const GET_ITEM_OPTIONS_DATA = "GET_ITEM_OPTIONS_DATA";
export const GET_ITEM_OPTIONS_DATA_SUCCESS = "GET_ITEM_OPTIONS_DATA_SUCCESS";
export const GET_ITEM_OPTIONS_DATA_FAILURE = "GET_ITEM_OPTIONS_DATA_FAILURE";

// enclosures
export const GET_ENCLOSURE_DATA = "GET_ENCLOSURE_DATA";
export const GET_ENCLOSURE_DATA_SUCCESS = "GET_ENCLOSURE_DATA_SUCCESS";
export const GET_ENCLOSURE_DATA_FAILURE = "GET_ENCLOSURE_DATA_FAILURE";

//shippingroute
export const GET_SHIPPING_ROUTES_DATA = "GET_SHIPPING_ROUTES_DATA";
export const GET_SHIPPING_ROUTES_DATA_SUCCESS =
  "GET_SHIPPING_ROUTES_DATA_SUCCESS";
export const GET_SHIPPING_ROUTES_DATA_FAILURE =
  "GET_SHIPPING_ROUTES_DATA_FAILURE";

//doctors
export const GET_DOCTORS_DATA = "GET_DOCTORS_DATA";
export const GET_DOCTORS_DATA_SUCCESS = "GET_DOCTORS_DATA_SUCCESS";
export const GET_DOCTORS_DATA_FAILURE = "GET_DOCTORS_DATA_FAILURE";
export const GET_CSV_DOCTORS_DATA = "GET_CSV_DOCTORS_DATA";
export const GET_CSV_DOCTORS_DATA_SUCCESS = "GET_CSV_DOCTORS_DATA_SUCCESS";
export const GET_CSV_DOCTORS_DATA_FAILURE = "GET_CSV_DOCTORS_DATA_FAILURE";
export const RESET_DOCTORS_PASSWORD = "RESET_DOCTORS_PASSWORD";
export const RESET_DOCTORS_PASSWORD_SUCCESS = "RESET_DOCTORS_PASSWORD_SUCCESS";
export const RESET_DOCTORS_PASSWORD_FAILURE = "RESET_DOCTORS_PASSWORD_FAILURE";
export const RESEND_DOCTORS_REGISTRATION_EMAIL =
  "RESEND_DOCTORS_REGISTRATION_EMAIL";
export const RESEND_DOCTORS_REGISTRATION_EMAIL_SUCCESS =
  "RESEND_DOCTORS_REGISTRATION_EMAIL_SUCCESS";
export const RESEND_DOCTORS_REGISTRATION_EMAIL_FAILURE =
  "RESEND_DOCTORS_REGISTRATION_EMAIL_FAILURE";
export const UNLOCK_DOCTORS = "UNLOCK_DOCTORS";
export const UNLOCK_DOCTORS_SUCCESS = "UNLOCK_DOCTORS_SUCCESS";
export const UNLOCK_DOCTORS_FAILURE = "UNLOCK_DOCTORS_FAILURE";
export const SEND_TO_LAB = "SEND_TO_LAB";
export const SEND_TO_LAB_SUCCESS = "SEND_TO_LAB_SUCCESS";
export const SEND_TO_LAB_FAILURE = "SEND_TO_LAB_FAILURE";
export const TOGGLE_ACTIVE = "TOGGLE_ACTIVE";
export const TOGGLE_ACTIVE_SUCCESS = "TOGGLE_ACTIVE_SUCCESS";
export const TOGGLE_ACTIVE_FAILURE = "TOGGLE_ACTIVE_FAILURE";

export const DELETE_DOCTORS_DATA = "DELETE_DOCTORS_DATA";
export const DELETE_DOCTORS_DATA_SUCCESS = "DELETE_DOCTORS_DATA_SUCCESS";
export const DELETE_DOCTORS_DATA_FAILURE = "DELETE_DOCTORS_DATA_FAILURE";

export const GET_DOCTORS_LIST = "GET_DOCTORS_LIST";
export const GET_DOCTORS_LIST_SUCCESS = "GET_DOCTORS_LIST_SUCCESS";
export const GET_DOCTORS_LIST_FAILURE = "GET_DOCTORS_LIST_FAILURE";

//organisation
export const GET_ORGANISATIONS_LIST = "GET_ORGANISATIONS_LIST";
export const GET_ORGANISATIONS_LIST_SUCCESS = "GET_ORGANISATIONS_LIST_SUCCESS";
export const GET_ORGANISATIONS_LIST_FAILURE = "GET_ORGANISATIONS_LIST_FAILURE";
